# This workflow will do a clean install of node dependencies, build the source code and run tests across selected node versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD-pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci frontend
        run: npm ci
        working-directory: frontend
      - name: lint frontend
        run: npm run lint
        working-directory: frontend
      - name: npm ci backend
        run: npm ci
        working-directory: backend
      - name: lint backend
        run: npm run lint
        working-directory: backend
      - name: build ui
        run: npm run build:ui
        working-directory: backend
      - name: Add backend remote origin
        run: git remote add heroku https://heroku:${{ secrets.HEROKU_TOKEN }}@git.heroku.com/club-webstore.git
      - name: Deploy backend to Heroku
        run: git subtree push --prefix backend heroku master