# This workflow will do a clean install of node dependencies, build the source code and run tests across selected node versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD-pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci frontend
        run: npm ci
        working-directory: frontend
      - name: lint frontend
        run: npm run lint
        working-directory: frontend
      - name: npm ci backend
        run: npm ci
        working-directory: backend
      - name: lint backend
        run: npm run lint
        working-directory: backend
      - name: build ui
        run: npm run build:ui
        working-directory: backend
      - name: Deploy backend
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_TOKEN}}
          heroku_app_name: "club-webstore"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "backend"
        env:
          MONGODB_URI: ${{secrets.MONGODB_URI}}
          HD_SECRET: ${{secrets.SECRET}}
          HD_APP_BASE: "backend"
